// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateAnswerRes interface {
	createAnswerRes()
}

type CreateQuestionRes interface {
	createQuestionRes()
}

type CreateTagRes interface {
	createTagRes()
}

type CreateUserRes interface {
	createUserRes()
}

type DeleteAnswerRes interface {
	deleteAnswerRes()
}

type DeleteQuestionRes interface {
	deleteQuestionRes()
}

type DeleteTagRes interface {
	deleteTagRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type ListAnswerRes interface {
	listAnswerRes()
}

type ListQuestionAnswersRes interface {
	listQuestionAnswersRes()
}

type ListQuestionRes interface {
	listQuestionRes()
}

type ListQuestionTagsRes interface {
	listQuestionTagsRes()
}

type ListTagQuestionsRes interface {
	listTagQuestionsRes()
}

type ListTagRes interface {
	listTagRes()
}

type ListUserAnswersRes interface {
	listUserAnswersRes()
}

type ListUserQuestionsRes interface {
	listUserQuestionsRes()
}

type ListUserRes interface {
	listUserRes()
}

type ListUserTagsRes interface {
	listUserTagsRes()
}

type ReadAnswerAuthorRes interface {
	readAnswerAuthorRes()
}

type ReadAnswerQuestionRes interface {
	readAnswerQuestionRes()
}

type ReadAnswerRes interface {
	readAnswerRes()
}

type ReadQuestionAuthorRes interface {
	readQuestionAuthorRes()
}

type ReadQuestionRes interface {
	readQuestionRes()
}

type ReadTagRes interface {
	readTagRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateAnswerRes interface {
	updateAnswerRes()
}

type UpdateQuestionRes interface {
	updateQuestionRes()
}

type UpdateTagRes interface {
	updateTagRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
