// Code generated by ogen, DO NOT EDIT.

package ogent

import (
	"github.com/go-faster/errors"
)

func (s ListAnswerOKApplicationJSON) Validate() error {
	alias := ([]AnswerList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListQuestionAnswersOKApplicationJSON) Validate() error {
	alias := ([]QuestionAnswersList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListQuestionOKApplicationJSON) Validate() error {
	alias := ([]QuestionList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListQuestionTagsOKApplicationJSON) Validate() error {
	alias := ([]QuestionTagsList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListTagOKApplicationJSON) Validate() error {
	alias := ([]TagList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListTagQuestionsOKApplicationJSON) Validate() error {
	alias := ([]TagQuestionsList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListUserAnswersOKApplicationJSON) Validate() error {
	alias := ([]UserAnswersList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListUserOKApplicationJSON) Validate() error {
	alias := ([]UserList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListUserQuestionsOKApplicationJSON) Validate() error {
	alias := ([]UserQuestionsList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListUserTagsOKApplicationJSON) Validate() error {
	alias := ([]UserTagsList)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
